name: deally_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.0
  #geolocator: ^9.0.0
  #http: ^0.13.4
  image_picker: ^0.8.5+3
  geocode: ^1.0.1
  #intl: ^0.17.0
  fluttertoast: ^8.0.9
  carousel_pro: ^1.0.0
  flutter_paystack: ^1.0.5+1
  uuid: ^3.0.6
  charts_flutter: ^0.12.0
  #webviewx: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Resolve_sans
      fonts:
        - asset: assets/fonts/Resolve_sans/Resolve-Black.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BlackCm.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BlackCmIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BlackCn.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BlackCnIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BlackExt.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BlackExtIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BlackIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BlackNrw.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BlackNrwIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BlackWd.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BlackWdIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-Bold.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BoldCm.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BoldCmIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BoldCn.otf
        - asset: assets/fonts/Resolve_sans/Resolve-BoldCnIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtraboldExt.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtraboldExtIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtraboldIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtraboldNrw.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtraboldNrwIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtraboldWd.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtraboldWdIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-Extralight.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtralightCm.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtralightCmIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtralightCn.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtralightCnIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtralightExt.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtralightExtIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtralightIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtralightNrw.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtralightNrwIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtralightWd.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ExtralightWdIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-Light.otf
        - asset: assets/fonts/Resolve_sans/Resolve-LightCmIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-LightCn.otf
        - asset: assets/fonts/Resolve_sans/Resolve-LightCnIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-LightExt.otf
        - asset: assets/fonts/Resolve_sans/Resolve-LightExtIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-LightIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-Lightm.otf
        - asset: assets/fonts/Resolve_sans/Resolve-LightNrw.otf
        - asset: assets/fonts/Resolve_sans/Resolve-LightNrwIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-LightWd.otf
        - asset: assets/fonts/Resolve_sans/Resolve-LightWdIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-Medium.otf
        - asset: assets/fonts/Resolve_sans/Resolve-MediumCn.otf
        - asset: assets/fonts/Resolve_sans/Resolve-MediumCnIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-MediumExt.otf
        - asset: assets/fonts/Resolve_sans/Resolve-MediumExtIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-MediumIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-MediumWd.otf
        - asset: assets/fonts/Resolve_sans/Resolve-MediumWdIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-Regular.otf
        - asset: assets/fonts/Resolve_sans/Resolve-RegularCm.otf
        - asset: assets/fonts/Resolve_sans/Resolve-RegularCmIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-RegularCn.otf
        - asset: assets/fonts/Resolve_sans/Resolve-RegularCnIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-RegularExt.otf
        - asset: assets/fonts/Resolve_sans/Resolve-RegularExtIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-RegularIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-RegularNrw.otf
        - asset: assets/fonts/Resolve_sans/Resolve-RegularNrwIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-RegularWd.otf
        - asset: assets/fonts/Resolve_sans/Resolve-RegularWdIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-Semibold.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemiboldCm.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemiboldCmIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemiboldExt.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemiboldExtIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemiboldIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemiboldNrw.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemiboldNrwIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemiboldWd.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemiboldWdIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-Semilight.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemilightCn.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemilightCnIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemilightExt.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemilightExtIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemilightIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemilightNrw.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemilightNrwIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemilightWd.otf
        - asset: assets/fonts/Resolve_sans/Resolve-SemilightWdIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-Thin.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ThinCm.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ThinCmIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ThinCn.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ThinCnIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ThinExt.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ThinExtIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ThinIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ThinNrw.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ThinNrwIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ThinWd.otf
        - asset: assets/fonts/Resolve_sans/Resolve-ThinWdIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-Ultralight.otf
        - asset: assets/fonts/Resolve_sans/Resolve-UltralightCmIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-UltralightCn.otf
        - asset: assets/fonts/Resolve_sans/Resolve-UltralightCnIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-UltralightExt.otf
        - asset: assets/fonts/Resolve_sans/Resolve-UltralightExtIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-UltralightIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-UltralightNrw.otf
        - asset: assets/fonts/Resolve_sans/Resolve-UltralightNrwIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-UltralightWdIta.otf
        - asset: assets/fonts/Resolve_sans/Resolve-UltralightWide.otf
    - family: Jeko
      fonts:
        - asset: assets/fonts/Jeko/Jeko Black Italic.ttf
        - asset: assets/fonts/Jeko/Jeko Black.ttf
        - asset: assets/fonts/Jeko/Jeko Bold Italic.ttf
        - asset: assets/fonts/Jeko/Jeko Bold.ttf
        - asset: assets/fonts/Jeko/Jeko Extra Bold Italic.ttf
        - asset: assets/fonts/Jeko/Jeko Extra Bold.ttf
        - asset: assets/fonts/Jeko/Jeko Extra Light Italic.ttf
        - asset: assets/fonts/Jeko/Jeko Extra Light.ttf
        - asset: assets/fonts/Jeko/Jeko Italic Variable.ttf
        - asset: assets/fonts/Jeko/Jeko Light Italic.ttf
        - asset: assets/fonts/Jeko/Jeko Light.ttf
        - asset: assets/fonts/Jeko/Jeko Medium Italic.ttf
        - asset: assets/fonts/Jeko/Jeko Medium.ttf
        - asset: assets/fonts/Jeko/Jeko Regular Italic.ttf
        - asset: assets/fonts/Jeko/Jeko Regular.ttf
        - asset: assets/fonts/Jeko/Jeko Semi Bold Italic.ttf
        - asset: assets/fonts/Jeko/Jeko Thin Italic.ttf
        - asset: assets/fonts/Jeko/Jeko Thin.ttf
        - asset: assets/fonts/Jeko/Jeko Variable.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
